//------------------------------------------------------------------------------------------
// File: CLabelTreeNode.h
// Desc: Representation of a label which is the target of a goto expr.
//       Only used in MIR form
// Auth: Lee Millward
//------------------------------------------------------------------------------------------

#ifndef __CLABELTREENODE_H__
#define __CLABELTREENODE_H__

#include "CTreeNode.h"
#include "CTreeNodeFactory.h"

/**
 * MIR specific tree node which represents the target location
 * of a CGotoExprTreeNode. Is only generated during MIR lowering
 * and should never appear in the higher level parse tree representation.
 */
class CLabelTreeNode : public CTreeNode
{
private:
	CLabelTreeNode(void) {}
	~CLabelTreeNode(void){}

	//only CTreeNodeFactory can instantiate tree nodes
	friend class CTreeNodeFactory;

public:

	/** Name of the label. */
	string Name;

	/**
	 * Inherited from CTreeNode. Should never be called.
	 * @see CTreeNode.
	 */
	void DumpAsParseTreeNode(TiXmlElement *XmlNode)
	{
		//shouldn't happen as label's don't appear in the
		//higher level representation
		InternalError("attempt to dump label tree node to parse tree");
	}

	/**
	 * Inherited from CTreeNode.
	 * @see CTreeNode.
	 */
	void DumpAsMIRTreeNode(ofstream &OutFile)
	{
		OutFile << Name << ":" << endl;
	}

	/**
	 * Inherited from CTreeNode. Should never be called.
	 * @see CTreeNode.
	 */
	CTreeNode* RewriteIntoMIRForm(CTreeNode *Stmts)
	{
		//since label expressions aren't generated by the parser,
		//we shouldn't have the situation where we're trying to rewrite
		//them into MIR form
		InternalError("attempt to rewrite label node into MIR form");
	}

	/**
	 * Inherited from CTreeNode.
	 * @see CTreeNode.
	 */
	CTreeNode* CreateCopy(void)
	{
		return CTreeNodeFactory::GetSingletonPtr()->BuildLabel(Name);
	}
};

#endif
